### ISSUE TITLE
Error by get Cookie

### ISSUE THREAD

**Issue by Agent3004** [arnekaiser/fastlane-plugin-huawei_appgallery#1]
Dear, 

After i would login i got this error. i login with the generated signing from the javacode i used the key from ClientID and Private from the AppGallery API section

[12:30:22]: ------------------------------
[12:30:22]: --- Step: default_platform ---
[12:30:22]: ------------------------------
[12:30:22]: Driving the lane 'android test' 🚀
[12:30:22]: -------------------------------
[12:30:22]: --- Step: huawei_appgallery ---
[12:30:22]: -------------------------------
[12:30:22]: Requesting cookie from Huawei AppGallery ...
+------------------+--------------+
|          Lane Context           |
+------------------+--------------+
| DEFAULT_PLATFORM | android      |
| PLATFORM_NAME    | android      |
| LANE_NAME        | android test |
+------------------+--------------+

+------+-------------------+-------------+
|            fastlane summary            |
+------+-------------------+-------------+
| Step | Action            | Time (in s) |
+------+-------------------+-------------+
| 1    | default_platform  | 0           |
| 💥   | huawei_appgallery | 0           |
+------+-------------------+-------------+

[12:30:22]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Users/klmacdevelopment/.rvm/gems/ruby-2.4.2/gems/fastlane-plugin-huawei_appgallery-0.1.0/lib/fastlane/plugin/huawei_appgallery/helper/huawei_appgallery_helper.rb:11:in `request_cookie': [!] undefined method `post' for Net::HTTP:Class (NoMethodError)
        from /Users/klmacdevelopment/.rvm/gems/ruby-2.4.2/gems/fastlane-plugin-huawei_appgallery-0.1.0/lib/fastlane/plugin/huawei_appgallery/actions/huawei_appgallery_action.rb:8:in `run'
        from /Users/klmacdevelopment/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
        from /Users/klmacdevelopment/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
        from /Users/klmacdevelopment/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
        from /Users/klmacdevelopment/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
        from /Users/klmacdevelopment/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
        from /Users/klmacdevelopment/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /Users/klmacdevelopment/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
        from Fastfile:47:in `block (2 levels) in parsing_binding'
        from /Users/klmacdevelopment/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /Users/klmacdevelopment/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /Users/klmacdevelopment/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /Users/klmacdevelopment/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /Users/klmacdevelopment/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
        from /Users/klmacdevelopment/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /Users/klmacdevelopment/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
        from /Users/klmacdevelopment/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from /Users/klmacdevelopment/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        from /Users/klmacdevelopment/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        from /Users/klmacdevelopment/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        from /Users/klmacdevelopment/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        from /Users/klmacdevelopment/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
        from /Users/klmacdevelopment/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        from /Users/klmacdevelopment/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
        from /Users/klmacdevelopment/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/bin/fastlane:23:in `<top (required)>'
        from /usr/local/bin/fastlane:23:in `load'
        from /usr/local/bin/fastlane:23:in `<main>'

desc "Publish pr in Huawei AppGallery "
lane :test do
  huawei_appgallery(
      client_id: "ODkwMDQ5MD*******DU5MTk4ZjZhOGZjNjY3MDQyY2Y5ZWJmYjVjMmNhNjllYjk1",
      time: "1568366070819",
      signature: "QkVvdMjPq8jj5IZB/Kk9C2Zhq5+4p9S9Stu86MHqbxBHsaN0/faXr9VDW4zQrI3tezcZok4xoqoAS3xszHdXxHf/t2wiNd0/CIGHCiMZSEBNK12************mB9o3f3o+Ne6TDU3UtOpmaK+dNCcmiOIOql5WXqGWk+bWIo1KAb+4gZjqUE8wXedC2Fm0K8DYPyxtg4qehtdxhGmnc5pPv8jJLXaQOo9uddH1DQv6AtSajZel7gB5k2x/uYhBIbi7mTdz2TKqyyBWbhcHlIQQku/h1OOE9Wz2l9oeyF7GdhlzAzzJ6ZICWCtekuzQ==",
      app_id: "156******54",
      release_notes: {
        "en-US" => "Bug fixes",
        "de-DE" => "Fehlerbehebungen"
      },
      apk_path: "test"
    )
end

**Comment by Agent3004** [comment]
Update Fastlane and bundels
